---
version: 0.1
runson: linux

autosplit: true
concurrency: 4

cypress: true
cypressOps:
  Build: "Hyperexecute Cypress Sample Build"
  Tags: ["HYP-Cypress", "Linux", "Autosplit", "Accessibility"]
  BuildTags: ["HYP-Cypress-v10"]

pre:
  - npm install
  - npm install cypress --save-dev
  - npm i lambdatest-cypress-cli

testDiscovery:
  mode: remote
  type: raw
  command: ls cypress/e2e/2-advanced-examples

testRunnerCommand: npx cypress run --spec ./cypress/e2e/2-advanced-examples/$test --browser=chrome-latest --headed --config video=true

jobLabel: [cypress-v10, linux, autosplit, remote]

background:
  - npm install node
  - cat /proc/cpuinfo
